import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./global/Header";
import Footer from "./global/Footer"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-w-[1440px] w-full bg-background text-text ">
          <div className="max-w-[1340px] m-auto pt-7 px-3">
            <Header />
        {children}
        <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
